/* Generated by scripts/build-plugin.mjs. Edit main.js and shared contract modules. */
/** Plugin export contract, independent of the Enterprise-only Variables REST API. */
function validateTokens(bundle, config) {
  if (bundle?.fileKey !== config.fileKey || bundle.schemaVersion !== 1) {
    throw new Error(
      "Token bundle does not match the configured Figma file/schema",
    );
  }
  const entries = Object.entries(bundle.modes ?? {});
  if (
    entries.length !== config.themeModes.length ||
    entries.some(([mode]) => !config.themeModes.includes(mode))
  ) {
    throw new Error("Token modes must exactly match configured profiles");
  }
  entries.sort(
    ([a], [b]) => config.themeModes.indexOf(a) - config.themeModes.indexOf(b),
  );
  let keys;
  for (const [, tokens] of entries) {
    const names = Object.keys(tokens).sort();
    if (names.length < 1 || names.length > 500)
      throw new Error("Invalid token count");
    if (keys && JSON.stringify(keys) !== JSON.stringify(names))
      throw new Error("Theme token names differ");
    keys = names;
    const cssNames = new Set();
    for (const [name, token] of Object.entries(tokens)) {
      if (!/^[a-z][a-z0-9/-]{1,100}$/.test(name))
        throw new Error("Unsafe token name");
      const cssName = name.replaceAll("/", "-");
      if (cssNames.has(cssName)) throw new Error("Colliding CSS token names");
      cssNames.add(cssName);
      if (token.type === "COLOR") {
        for (const channel of ["r", "g", "b", "a"]) {
          const number = token.value?.[channel];
          if (!Number.isFinite(number) || number < 0 || number > 1)
            throw new Error("Invalid colour");
        }
      } else if (token.type === "FLOAT") {
        if (
          !Number.isFinite(token.value) ||
          token.value < 0 ||
          token.value > 10000
        )
          throw new Error("Invalid numeric token");
        if (name.startsWith("opacity/") && token.value > 100)
          throw new Error("Figma opacity must be a percentage from 0 to 100");
      } else if (token.type === "STRING") {
        const font =
          /^typography\/[a-z0-9-]+\/family$/.test(name) &&
          ["Manrope", "Fraunces", "Newsreader", "JetBrains Mono"].includes(
            token.value,
          );
        const easing =
          /^motion\/easing\/[a-z-]+$/.test(name) &&
          typeof token.value === "string" &&
          /^cubic-bezier\(\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*\)$/.test(
            token.value,
          );
        if (!font && !easing)
          throw new Error("Unsupported or unsafe string token");
      } else throw new Error("Unsupported token type");
    }
  }
  // Remove timestamps and any additional plugin input from committed data.
  return {
    schemaVersion: 1,
    fileKey: config.fileKey,
    modes: Object.fromEntries(
      entries.map(([mode, tokens]) => [
        mode,
        Object.fromEntries(
          Object.keys(tokens)
            .sort()
            .map((name) => [
              name,
              { type: tokens[name].type, value: tokens[name].value },
            ]),
        ),
      ]),
    ),
  };
}

function tokenCss(bundle) {
  const css = [
    "/* Generated Meridian reference tokens. Reviewed adaptation into a product is required. */",
  ];
  for (const [mode, tokens] of Object.entries(bundle.modes)) {
    const selectors = {
      Dawn: ':root, [data-meridian="grass"]',
      Dusk: '.dark:not([data-meridian]), [data-meridian="grass"][data-theme="dark"], [data-meridian="grass"].dark:not([data-theme="light"])',
      PaperDawn: '[data-meridian="paper"]',
      PaperDusk:
        '[data-meridian="paper"][data-theme="dark"], [data-meridian="paper"].dark:not([data-theme="light"])',
    };
    if (!selectors[mode]) throw new Error("Unsupported CSS theme mode");
    css.push(`${selectors[mode]} {`);
    for (const [name, token] of Object.entries(tokens)) {
      let value = token.value;
      if (token.type === "COLOR") {
        const { r, g, b, a } = value;
        value = `rgb(${Math.round(r * 255)} ${Math.round(g * 255)} ${Math.round(b * 255)} / ${Number(a.toFixed(4))})`;
      } else if (token.type === "STRING") {
        value = name.endsWith("/family") ? JSON.stringify(value) : value;
      } else {
        value = Number(value.toFixed(4));
        if (name.startsWith("opacity/"))
          value = Number((value / 100).toFixed(4));
        else if (name.startsWith("motion/duration/")) value = `${value}ms`;
        else if (
          /^(spacing|radius|size|layout|blur|stroke|focus|breakpoint|elevation)\//.test(
            name,
          ) ||
          /^typography\/[^/]+\/(size|line-height|letter-spacing)$/.test(name) ||
          /^grid\/[^/]+\/(gutter|margin)$/.test(name) ||
          name.startsWith("motion/translate/")
        )
          value = `${value}px`;
      }
      css.push(`  --meridian-${name.replaceAll("/", "-")}: ${value};`);
    }
    css.push("}", "");
  }
  return css.join("\n");
}

const websiteAliases = `[data-meridian] {
  --md-font-display: var(--md-typography-h1-family);
  --md-font-body: var(--md-typography-button-family);
  --md-font-reading: var(--md-typography-reading-family);
  --md-font-label: var(--md-typography-button-family);
  --md-motion-hover: var(--md-motion-duration-hover);
  --md-motion-button: var(--md-motion-duration-release);
  --md-ease: var(--md-motion-easing-settle);
  color-scheme: light;
}
[data-meridian][data-theme="dark"] { color-scheme: dark; }
`;

function websiteCss(bundle) {
  return (
    "/* Generated from design/figma/generated/tokens.json; do not edit. */\n" +
    tokenCss(bundle)
      .split("\n")
      .slice(1)
      .join("\n")
      .replaceAll("--meridian-", "--md-") +
    "\n" +
    websiteAliases
  );
}

const modes = ["Dawn", "Dusk", "PaperDawn", "PaperDusk"];
const fileKey = "aJ2f6aYX9KBucAdPsCmkXn";
function validateContent(content, template) {
  if (content?.schemaVersion !== 1 || content.fileKey !== fileKey)
    throw Error("Wrong shared-content file/schema");
  const names = Object.keys(template.fields).sort();
  if (
    JSON.stringify(Object.keys(content.fields ?? {}).sort()) !==
    JSON.stringify(names)
  )
    throw Error("Shared-content fields differ");
  const fields = {};
  for (const name of names) {
    const field = content.fields[name],
      expected = template.fields[name];
    if (
      field.nodeId !== expected.nodeId ||
      field.pageId !== expected.pageId ||
      typeof field.value !== "string" ||
      field.value.length > 4000
    )
      throw Error("Invalid shared-content field: " + name);
    fields[name] = {
      nodeId: field.nodeId,
      pageId: field.pageId,
      value: field.value,
    };
  }
  return { schemaVersion: 1, fileKey, fields };
}
function extractContent(document, template) {
  const byId = {};
  const visit = (n) => {
    byId[n.id] = n;
    for (const child of n.children ?? []) visit(child);
  };
  visit(document);
  const fields = {};
  for (const [name, field] of Object.entries(template.fields)) {
    const n = byId[field.nodeId];
    if (n?.type !== "TEXT")
      throw Error(
        "Named version lacks current shared content: " +
          name +
          ". Save a new version of the current library.",
      );
    fields[name] = { ...field, value: n.characters };
  }
  return validateContent({ schemaVersion: 1, fileKey, fields }, template);
}
function signature(value) {
  const normal = (v) =>
    typeof v === "number"
      ? Number(v.toFixed(6))
      : Array.isArray(v)
        ? v.map(normal)
        : v && typeof v === "object"
          ? Object.fromEntries(
              Object.keys(v)
                .sort()
                .map((k) => [k, normal(v[k])]),
            )
          : v;
  return JSON.stringify(normal(value));
}
function syncDirection(base, local, remote) {
  const l = signature(local),
    r = signature(remote);
  if (l === r) return "equal";
  if (!base) return "choose";
  const b = signature(base);
  if (l === b) return "import";
  if (r === b) return "publish";
  return "conflict";
}
function captureNativeTokens(collections, variables) {
  const cs = Object.fromEntries(collections.map((c) => [c.id, c])),
    vs = Object.fromEntries(variables.map((v) => [v.id, v]));
  const resolve = (v, theme, seen = new Set()) => {
    if (!v || seen.has(v.id)) throw Error("Missing or cyclic alias");
    seen.add(v.id);
    const c = cs[v.variableCollectionId];
    let m =
      c.modes.find((m) => m.name === theme) ||
      c.modes.find(
        (m) => m.name === (theme.startsWith("Paper") ? "Paper" : "Grass"),
      );
    if (
      !m &&
      c.modes.length === 1 &&
      !["Meridian / Colour", "Meridian / Layout", "Meridian / Motion"].includes(
        c.name,
      )
    )
      m = c.modes[0];
    if (!m) throw Error("Missing profile mode in " + c.name);
    const value = v.valuesByMode[m.modeId];
    return value?.type === "VARIABLE_ALIAS"
      ? resolve(vs[value.id], theme, seen)
      : value;
  };
  const semantic = variables.filter(
    (v) =>
      cs[v.variableCollectionId]?.name.startsWith("Meridian /") &&
      cs[v.variableCollectionId]?.name !== "Meridian / Primitives" &&
      ["COLOR", "FLOAT", "STRING"].includes(v.resolvedType),
  );
  return validateTokens(
    {
      schemaVersion: 1,
      fileKey,
      modes: Object.fromEntries(
        modes.map((theme) => [
          theme,
          Object.fromEntries(
            semantic.map((v) => [
              v.name,
              { type: v.resolvedType, value: resolve(v, theme) },
            ]),
          ),
        ]),
      ),
    },
    { fileKey, themeModes: modes },
  );
}
function planTokenImport(bundle, collections, variables) {
  const candidate = validateTokens(bundle, { fileKey, themeModes: modes });
  const cs = Object.fromEntries(collections.map((c) => [c.id, c])),
    vs = Object.fromEntries(variables.map((v) => [v.id, v]));
  const semantic = variables.filter(
    (v) =>
      cs[v.variableCollectionId]?.name.startsWith("Meridian /") &&
      cs[v.variableCollectionId]?.name !== "Meridian / Primitives" &&
      ["FLOAT", "COLOR", "STRING"].includes(v.resolvedType),
  );
  const localNames = semantic.map((v) => v.name).sort();
  if (
    JSON.stringify(localNames) !==
    JSON.stringify(Object.keys(candidate.modes.Dawn).sort())
  )
    throw Error(
      "Import requires the same semantic token names; new tokens need a library update",
    );
  const terminal = (v, theme, seen = new Set()) => {
    if (!v || seen.has(v.id)) throw Error("Missing or cyclic alias");
    seen.add(v.id);
    const c = cs[v.variableCollectionId];
    let m =
      c.modes.find((m) => m.name === theme) ||
      c.modes.find(
        (m) => m.name === (theme.startsWith("Paper") ? "Paper" : "Grass"),
      );
    if (
      !m &&
      c.modes.length === 1 &&
      !["Meridian / Colour", "Meridian / Layout", "Meridian / Motion"].includes(
        c.name,
      )
    )
      m = c.modes[0];
    if (!m) throw Error("Missing profile mode: " + c.name);
    const current = v.valuesByMode[m.modeId];
    return current?.type === "VARIABLE_ALIAS"
      ? terminal(vs[current.id], theme, seen)
      : { id: v.id, modeId: m.modeId, type: v.resolvedType, current };
  };
  const cells = new Map();
  for (const theme of modes)
    for (const v of semantic) {
      const token = candidate.modes[theme][v.name];
      if (token.type !== v.resolvedType)
        throw Error("Token type differs: " + v.name);
      const cell = terminal(v, theme);
      const key = cell.id + "@" + cell.modeId;
      if (cell.type !== token.type) throw Error("Alias type differs");
      const previous = cells.get(key);
      if (previous && signature(previous.value) !== signature(token.value))
        throw Error(
          "Shared alias has conflicting values: " +
            v.name +
            ". Update all roles sharing this primitive together.",
        );
      cells.set(key, { ...cell, value: token.value });
    }
  return [...cells.values()].filter(
    (c) => signature(c.current) !== signature(c.value),
  );
}

const contentTemplate={"schemaVersion":1,"fileKey":"aJ2f6aYX9KBucAdPsCmkXn","fields":{"heroTitle":{"nodeId":"92:37","pageId":"92:34"},"heroDescription":{"nodeId":"92:38","pageId":"92:34"},"coreTitle":{"nodeId":"92:40","pageId":"92:34"},"coreDescription":{"nodeId":"92:41","pageId":"92:34"},"grassTitle":{"nodeId":"92:43","pageId":"92:34"},"grassDescription":{"nodeId":"92:44","pageId":"92:34"},"paperTitle":{"nodeId":"92:46","pageId":"92:34"},"paperDescription":{"nodeId":"92:47","pageId":"92:34"},"extendTitle":{"nodeId":"92:49","pageId":"92:34"},"extendDescription":{"nodeId":"92:50","pageId":"92:34"}}};
figma.showUI(__html__, { width: 480, height: 600 });
async function capture() {
  if (figma.fileKey && figma.fileKey !== fileKey)
    throw Error("Open the configured Meridian file");
  const collections = await figma.variables.getLocalVariableCollectionsAsync(),
    variables = await figma.variables.getLocalVariablesAsync();
  const tokens = captureNativeTokens(collections, variables);
  const fields = {};
  for (const [name, field] of Object.entries(contentTemplate.fields)) {
    const n = await figma.getNodeByIdAsync(field.nodeId);
    if (n?.type !== "TEXT") throw Error("Missing shared text: " + name);
    fields[name] = { ...field, value: n.characters };
  }
  return {
    tokens,
    content: validateContent(
      { schemaVersion: 1, fileKey, fields },
      contentTemplate,
    ),
    collections,
    variables,
  };
}
figma.ui.onmessage = async (message) => {
  try {
    const local = await capture();
    const bundle = { tokens: local.tokens, content: local.content };
    if (message.type === "export") {
      figma.ui.postMessage({ type: "tokens", ...bundle });
      return;
    }
    if (message.type !== "import") return;
    if (signature(bundle) !== message.expectedLocalSignature)
      throw Error(
        "Figma changed since comparison. Compare again before importing.",
      );
    const content = validateContent(message.bundle.content, contentTemplate);
    const writes = planTokenImport(
      message.bundle.tokens,
      local.collections,
      local.variables,
    );
    const familyWrites = writes.filter((w) =>
      local.variables
        .find((v) => v.id === w.id)
        ?.scopes?.includes("FONT_FAMILY"),
    );
    if (familyWrites.length) {
      const families = new Set(
        familyWrites.flatMap((w) => [w.value, w.current]),
      );
      const fonts = await figma.listAvailableFontsAsync();
      for (const font of fonts.filter((f) => families.has(f.fontName.family)))
        await figma.loadFontAsync(font.fontName);
    }
    const texts = [];
    for (const [name, field] of Object.entries(content.fields)) {
      const n = await figma.getNodeByIdAsync(field.nodeId);
      if (n?.type !== "TEXT") throw Error("Missing shared text");
      if (n.characters !== field.value) {
        const segments = n.getStyledTextSegments(["fontName"]);
        if (!segments.length) segments.push({ fontName: n.fontName });
        for (const part of segments) {
          if (!part.fontName || part.fontName === figma.mixed)
            throw Error(
              "Resolve the missing/mixed font before importing shared text.",
            );
          await figma.loadFontAsync(part.fontName);
        }
        texts.push({ n, old: n.characters, value: field.value });
      }
    }
    // Font loading yields to the editor; protect edits made during preparation.
    const prepared = await capture();
    if (
      signature({ tokens: prepared.tokens, content: prepared.content }) !==
      message.expectedLocalSignature
    )
      throw Error("Figma changed while preparing the import. Compare again.");
    const vs = Object.fromEntries(local.variables.map((v) => [v.id, v]));
    const applied = [],
      edited = [];
    try {
      for (const w of writes) {
        vs[w.id].setValueForMode(w.modeId, w.value);
        applied.push(w);
      }
      for (const t of texts) {
        t.n.characters = t.value;
        edited.push(t);
      }
    } catch (error) {
      for (const t of edited.reverse()) t.n.characters = t.old;
      for (const w of applied.reverse())
        vs[w.id].setValueForMode(w.modeId, w.current);
      throw error;
    }
    const next = await capture();
    figma.ui.postMessage({
      type: "imported",
      tokens: next.tokens,
      content: next.content,
      variableCells: writes.length,
      textNodes: texts.length,
    });
  } catch (error) {
    figma.ui.postMessage({ type: "error", message: error.message });
  }
};
