/* Generated by scripts/build-plugin.mjs. Edit main.js and shared contract modules. */
/** Plugin export contract, independent of the Enterprise-only Variables REST API. */
const profiles = [
  { id: "grass", name: "Grass", light: "Dawn", dark: "Dusk" },
  { id: "paper", name: "Paper", light: "PaperDawn", dark: "PaperDusk" },
  { id: "core", name: "Core", light: "CoreDawn", dark: "CoreDusk" },
  { id: "parallel", name: "Parallel", light: "ParallelDawn", dark: "ParallelDusk", projectColour: true },
  { id: "canvas", name: "Canvas", light: "CanvasDawn", dark: "CanvasDusk", projectColour: true },
  { id: "gallery", name: "Gallery", light: "GalleryDawn", dark: "GalleryDusk", projectColour: true },
];

function profileForMode(mode) {
  const profile = profiles.find(p => p.light === mode || p.dark === mode);
  if (!profile) throw Error("Unsupported CSS theme mode");
  return { ...profile, nativeName: profile.name + " / " + (profile.light === mode ? "Dawn" : "Dusk") };
}

function validateTokens(bundle, config) {
  if (bundle?.fileKey !== config.fileKey || bundle.schemaVersion !== 1) {
    throw new Error(
      "Token bundle does not match the configured Figma file/schema",
    );
  }
  const entries = Object.entries(bundle.modes ?? {});
  if (
    entries.length !== config.themeModes.length ||
    entries.some(([mode]) => !config.themeModes.includes(mode))
  ) {
    throw new Error("Token modes must exactly match configured profiles");
  }
  entries.sort(
    ([a], [b]) => config.themeModes.indexOf(a) - config.themeModes.indexOf(b),
  );
  let keys;
  for (const [, tokens] of entries) {
    const names = Object.keys(tokens).sort();
    if (names.length < 1 || names.length > 500)
      throw new Error("Invalid token count");
    if (keys && JSON.stringify(keys) !== JSON.stringify(names))
      throw new Error("Theme token names differ");
    keys = names;
    const cssNames = new Set();
    for (const [name, token] of Object.entries(tokens)) {
      if (!/^[a-z][a-z0-9/-]{1,100}$/.test(name))
        throw new Error("Unsafe token name");
      const cssName = name.replaceAll("/", "-");
      if (cssNames.has(cssName)) throw new Error("Colliding CSS token names");
      cssNames.add(cssName);
      if (token.type === "COLOR") {
        for (const channel of ["r", "g", "b", "a"]) {
          const number = token.value?.[channel];
          if (!Number.isFinite(number) || number < 0 || number > 1)
            throw new Error("Invalid colour");
        }
      } else if (token.type === "FLOAT") {
        if (
          !Number.isFinite(token.value) ||
          token.value < 0 ||
          token.value > 10000
        )
          throw new Error("Invalid numeric token");
        if (name.startsWith("opacity/") && token.value > 100)
          throw new Error("Figma opacity must be a percentage from 0 to 100");
      } else if (token.type === "STRING") {
        const font =
          /^typography\/[a-z0-9-]+\/family$/.test(name) &&
          ["Manrope", "Fraunces", "Newsreader", "JetBrains Mono", "Geist", "Geist Mono", "Inter", "Cormorant Garamond"].includes(
            token.value,
          );
        const easing =
          /^motion\/easing\/[a-z-]+$/.test(name) &&
          typeof token.value === "string" &&
          /^cubic-bezier\(\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*,\s*(?:0(?:\.\d+)?|1(?:\.0+)?)\s*\)$/.test(
            token.value,
          );
        if (!font && !easing)
          throw new Error("Unsupported or unsafe string token");
      } else throw new Error("Unsupported token type");
    }
  }
  // Remove timestamps and any additional plugin input from committed data.
  return {
    schemaVersion: 1,
    fileKey: config.fileKey,
    modes: Object.fromEntries(
      entries.map(([mode, tokens]) => [
        mode,
        Object.fromEntries(
          Object.keys(tokens)
            .sort()
            .map((name) => [
              name,
              { type: tokens[name].type, value: tokens[name].value },
            ]),
        ),
      ]),
    ),
  };
}

function tokenCss(bundle) {
  const css = [
    "/* Generated Meridian reference tokens. Reviewed adaptation into a product is required. */",
  ];
  for (const [mode, tokens] of Object.entries(bundle.modes)) {
    const profile = profileForMode(mode);
    const selector = `[data-meridian="${profile.id}"]`;
    const light = profile.light === mode;
    const selectors = light
      ? (profile.id === "grass" ? ":root, " : "") + selector
      : (profile.id === "grass" ? ".dark:not([data-meridian]), " : "") + `${selector}[data-theme="dark"], ${selector}.dark:not([data-theme="light"])`;
    css.push(`${selectors} {`);
    for (const [name, token] of Object.entries(tokens)) {
      let value = token.value;
      if (token.type === "COLOR") {
        const { r, g, b, a } = value;
        value = `rgb(${Math.round(r * 255)} ${Math.round(g * 255)} ${Math.round(b * 255)} / ${Number(a.toFixed(4))})`;
      } else if (token.type === "STRING") {
        value = name.endsWith("/family") ? JSON.stringify(value) : value;
      } else {
        value = Number(value.toFixed(4));
        if (name.startsWith("opacity/"))
          value = Number((value / 100).toFixed(4));
        else if (name.startsWith("motion/duration/")) value = `${value}ms`;
        else if (
          /^(spacing|radius|size|layout|blur|stroke|focus|breakpoint|elevation)\//.test(
            name,
          ) ||
          /^typography\/[^/]+\/(size|line-height|letter-spacing)$/.test(name) ||
          /^grid\/[^/]+\/(gutter|margin)$/.test(name) ||
          name.startsWith("motion/translate/")
        )
          value = `${value}px`;
      }
      css.push(`  --meridian-${name.replaceAll("/", "-")}: ${value};`);
    }
    css.push("}", "");
  }
  return css.join("\n");
}

const websiteAliases = `[data-meridian] {
  --md-font-display: var(--md-typography-h1-family);
  --md-font-body: var(--md-typography-reading-family);
  --md-font-reading: var(--md-typography-reading-family);
  --md-font-label: var(--md-typography-button-family);
  --md-font-code: var(--md-typography-code-family);
  --md-motion-hover: var(--md-motion-duration-hover);
  --md-motion-button: var(--md-motion-duration-release);
  --md-ease: var(--md-motion-easing-settle);
  color-scheme: light;
}
[data-meridian][data-theme="dark"] { color-scheme: dark; }
`;

function websiteCss(bundle) {
  return (
    "/* Generated from design/figma/generated/tokens.json; do not edit. */\n" +
    tokenCss(bundle)
      .split("\n")
      .slice(1)
      .join("\n")
      .replaceAll("--meridian-", "--md-") +
    "\n" +
    websiteAliases
  );
}

const modes = profiles.flatMap(p => [p.light, p.dark]);
const fileKey = "aJ2f6aYX9KBucAdPsCmkXn";
function modeForCollection(collection, theme) {
  const profile = profileForMode(theme);
  const match = collection.modes.find(m => m.name === profile.nativeName || m.name === theme)
    || collection.modes.find(m => m.name === profile.name);
  if (match) return match;
  if (collection.modes.length === 1 && !["Meridian / Colour", "Meridian / Project Colour", "Meridian / Layout", "Meridian / Motion"].includes(collection.name)) return collection.modes[0];
  throw Error("Missing profile mode in " + collection.name);
}
function semanticForMode(variables, collections, theme) {
  const colour = profileForMode(theme).projectColour ? "Meridian / Project Colour" : "Meridian / Colour";
  return variables.filter(v => {
    const name = collections[v.variableCollectionId]?.name;
    return name?.startsWith("Meridian /") && name !== "Meridian / Primitives"
      && (!name.endsWith("Colour") || name === colour)
      && ["COLOR", "FLOAT", "STRING"].includes(v.resolvedType);
  });
}
function validateContent(content, template) {
  if (content?.schemaVersion !== 1 || content.fileKey !== fileKey)
    throw Error("Wrong shared-content file/schema");
  const names = Object.keys(template.fields).sort();
  if (
    JSON.stringify(Object.keys(content.fields ?? {}).sort()) !==
    JSON.stringify(names)
  )
    throw Error("Shared-content fields differ");
  const fields = {};
  for (const name of names) {
    const field = content.fields[name],
      expected = template.fields[name];
    if (
      field.nodeId !== expected.nodeId ||
      field.pageId !== expected.pageId ||
      typeof field.value !== "string" ||
      field.value.length > 4000
    )
      throw Error("Invalid shared-content field: " + name);
    fields[name] = {
      nodeId: field.nodeId,
      pageId: field.pageId,
      value: field.value,
    };
  }
  return { schemaVersion: 1, fileKey, fields };
}
function extractContent(document, template) {
  const byId = {};
  const visit = (n) => {
    byId[n.id] = n;
    for (const child of n.children ?? []) visit(child);
  };
  visit(document);
  const fields = {};
  for (const [name, field] of Object.entries(template.fields)) {
    const n = byId[field.nodeId];
    if (n?.type !== "TEXT")
      throw Error(
        "Named version lacks current shared content: " +
          name +
          ". Save a new version of the current library.",
      );
    fields[name] = { ...field, value: n.characters };
  }
  return validateContent({ schemaVersion: 1, fileKey, fields }, template);
}
function signature(value) {
  const normal = (v) =>
    typeof v === "number"
      ? Number(v.toFixed(6))
      : Array.isArray(v)
        ? v.map(normal)
        : v && typeof v === "object"
          ? Object.fromEntries(
              Object.keys(v)
                .sort()
                .map((k) => [k, normal(v[k])]),
            )
          : v;
  return JSON.stringify(normal(value));
}
function syncDirection(base, local, remote) {
  const l = signature(local),
    r = signature(remote);
  if (l === r) return "equal";
  if (!base) return "choose";
  const b = signature(base);
  if (l === b) return "import";
  if (r === b) return "publish";
  return "conflict";
}
function captureNativeTokens(collections, variables) {
  const cs = Object.fromEntries(collections.map((c) => [c.id, c])),
    vs = Object.fromEntries(variables.map((v) => [v.id, v]));
  const resolve = (v, theme, seen = new Set()) => {
    if (!v || seen.has(v.id)) throw Error("Missing or cyclic alias");
    seen.add(v.id);
    const c = cs[v.variableCollectionId];
    const m = modeForCollection(c, theme);
    const value = v.valuesByMode[m.modeId];
    return value?.type === "VARIABLE_ALIAS"
      ? resolve(vs[value.id], theme, seen)
      : value;
  };
  return validateTokens(
    {
      schemaVersion: 1,
      fileKey,
      modes: Object.fromEntries(
        modes.map((theme) => [
          theme,
          Object.fromEntries(
            semanticForMode(variables, cs, theme).map((v) => [
              v.name,
              { type: v.resolvedType, value: resolve(v, theme) },
            ]),
          ),
        ]),
      ),
    },
    { fileKey, themeModes: modes },
  );
}
function planTokenImport(bundle, collections, variables) {
  const candidate = validateTokens(bundle, { fileKey, themeModes: modes });
  const cs = Object.fromEntries(collections.map((c) => [c.id, c])),
    vs = Object.fromEntries(variables.map((v) => [v.id, v]));
  const localNames = semanticForMode(variables, cs, modes[0]).map(v => v.name).sort();
  if (
    JSON.stringify(localNames) !==
    JSON.stringify(Object.keys(candidate.modes.Dawn).sort())
  )
    throw Error(
      "Import requires the same semantic token names; new tokens need a library update",
    );
  const terminal = (v, theme, seen = new Set()) => {
    if (!v || seen.has(v.id)) throw Error("Missing or cyclic alias");
    seen.add(v.id);
    const c = cs[v.variableCollectionId];
    const m = modeForCollection(c, theme);
    const current = v.valuesByMode[m.modeId];
    return current?.type === "VARIABLE_ALIAS"
      ? terminal(vs[current.id], theme, seen)
      : { id: v.id, modeId: m.modeId, type: v.resolvedType, current };
  };
  const cells = new Map();
  for (const theme of modes)
    for (const v of semanticForMode(variables, cs, theme)) {
      const token = candidate.modes[theme][v.name];
      if (token.type !== v.resolvedType)
        throw Error("Token type differs: " + v.name);
      const cell = terminal(v, theme);
      const key = cell.id + "@" + cell.modeId;
      if (cell.type !== token.type) throw Error("Alias type differs");
      const previous = cells.get(key);
      if (previous && signature(previous.value) !== signature(token.value))
        throw Error(
          "Shared alias has conflicting values: " +
            v.name +
            ". Update all roles sharing this primitive together.",
        );
      cells.set(key, { ...cell, value: token.value });
    }
  return [...cells.values()].filter(
    (c) => signature(c.current) !== signature(c.value),
  );
}

/**
 * Meridian 0.6 Lab-only GitHub -> Figma Forest contract.
 * No stable Meridian 0.5 collection, component or token is writable here.
 */
const FOREST_ROLES = Object.freeze([
  'page','surface','text','muted','border','action','onAction','focus',
  'sunlight','canopy','earth','ambient'
]);

const sameKeys=(a,b)=>JSON.stringify(Object.keys(a).sort())===JSON.stringify(Object.keys(b).sort());
const hexRe=/^#[0-9A-F]{6}$/;

function validateForestContract(input,template) {
  if(!input||input.schemaVersion!==1||input.fileKey!==template.fileKey||
    input.pageId!==template.pageId||input.collectionName!==template.collectionName||
    input.source!=='lab/forest-reference/forest-model.js')
    throw Error('Forest contract file, page, collection or schema mismatch');
  if(!sameKeys(input.modes||{}, {Dawn:1,Dusk:1}))
    throw Error('Forest requires Dawn and Dusk modes only');
  const modes={};
  for(const mode of ['Dawn','Dusk']){
    const palette=input.modes[mode];
    if(!palette||!sameKeys(palette,Object.fromEntries(FOREST_ROLES.map(r=>[r,1]))))
      throw Error('Forest palette roles differ: '+mode);
    modes[mode]={};
    for(const role of FOREST_ROLES){
      const h=palette[role];
      if(typeof h!=='string'||!hexRe.test(h.toUpperCase()))
        throw Error('Invalid Forest colour: '+mode+'/'+role);
      modes[mode][role]=h.toUpperCase();
    }
  }
  if(!sameKeys(input.fields||{},template.fields||{}))
    throw Error('Forest text field names differ');
  const fields={};
  for(const name of Object.keys(template.fields).sort()){
    const field=input.fields[name],expected=template.fields[name];
    if(field?.nodeId!==expected.nodeId||field.pageId!==template.pageId||
      typeof field.value!=='string'||field.value.length>280||
      /[\x00-\x08\x0B\x0E-\x1F]/.test(field.value))
      throw Error('Forest text field not authorised: '+name);
    fields[name]={nodeId:expected.nodeId,pageId:template.pageId,value:field.value};
  }
  return {schemaVersion:1,fileKey:template.fileKey,pageId:template.pageId,
    collectionName:template.collectionName,source:input.source,modes,fields};
}

function hexToFigmaColor(hex) {
  if(!hexRe.test(hex.toUpperCase()))throw Error('Invalid Forest hex');
  return {r:parseInt(hex.slice(1,3),16)/255,
    g:parseInt(hex.slice(3,5),16)/255,
    b:parseInt(hex.slice(5,7),16)/255,a:1};
}
function figmaColorToHex(c) {
  if(!c||['r','g','b'].some(k=>!Number.isFinite(c[k])||c[k]<0||c[k]>1)||
    (c.a!==undefined && (!Number.isFinite(c.a)||c.a<.999)))
    throw Error('Forest requires an opaque direct colour value');
  return '#'+['r','g','b'].map(k=>Math.round(c[k]*255).toString(16).padStart(2,'0')).join('').toUpperCase();
}

function planForestImport(remote,local,template) {
  const target=validateForestContract(remote,template);
  const now=validateForestContract(local,template);
  const values=[],texts=[];
  for(const mode of ['Dawn','Dusk'])
    for(const role of FOREST_ROLES)
      if(target.modes[mode][role]!==now.modes[mode][role])
        values.push({mode,role,from:now.modes[mode][role],to:target.modes[mode][role]});
  for(const name of Object.keys(target.fields))
    if(target.fields[name].value!==now.fields[name].value)
      texts.push({name,nodeId:target.fields[name].nodeId,
        from:now.fields[name].value,to:target.fields[name].value});
  return {values,texts};
}

const forestTemplate={"schemaVersion":1,"fileKey":"aJ2f6aYX9KBucAdPsCmkXn","pageId":"218:21","collectionName":"Meridian 0.6 Lab / Forest","source":"lab/forest-reference/forest-model.js","modes":{"Dawn":{"page":"#EDF1E6","surface":"#FCFDF8","text":"#243B2E","muted":"#435B49","border":"#94AB97","action":"#22583E","onAction":"#FFFFFF","focus":"#22583E","sunlight":"#E7E2B8","canopy":"#9CB8A1","earth":"#70886B","ambient":"#D6E4D0"},"Dusk":{"page":"#293B33","surface":"#354D40","text":"#F8F6E9","muted":"#E1E8D9","border":"#A6B7A4","action":"#F0D7A6","onAction":"#253A30","focus":"#FFE0A2","sunlight":"#C5A477","canopy":"#6E967D","earth":"#476C57","ambient":"#4B6556"}},"fields":{"dawnTitle":{"nodeId":"219:15","pageId":"218:21"},"dawnDescription":{"nodeId":"219:16","pageId":"218:21"},"dawnHistoryTitle":{"nodeId":"219:51","pageId":"218:21"},"duskTitle":{"nodeId":"219:70","pageId":"218:21"},"duskDescription":{"nodeId":"219:71","pageId":"218:21"},"duskHistoryTitle":{"nodeId":"219:106","pageId":"218:21"}}};
const contentTemplate={"schemaVersion":1,"fileKey":"aJ2f6aYX9KBucAdPsCmkXn","fields":{"coreDescription":{"nodeId":"92:41","pageId":"92:34"},"coreTitle":{"nodeId":"92:40","pageId":"92:34"},"extendDescription":{"nodeId":"92:50","pageId":"92:34"},"extendTitle":{"nodeId":"92:49","pageId":"92:34"},"grassDescription":{"nodeId":"92:44","pageId":"92:34"},"grassTitle":{"nodeId":"92:43","pageId":"92:34"},"heroDescription":{"nodeId":"92:38","pageId":"92:34"},"heroTitle":{"nodeId":"92:37","pageId":"92:34"},"paperDescription":{"nodeId":"92:47","pageId":"92:34"},"paperTitle":{"nodeId":"92:46","pageId":"92:34"}}};
figma.showUI(__html__, { width: 480, height: 600 });
async function capture() {
  if (figma.fileKey && figma.fileKey !== fileKey)
    throw Error("Open the configured Meridian file");
  const collections = await figma.variables.getLocalVariableCollectionsAsync(),
    variables = await figma.variables.getLocalVariablesAsync();
  const tokens = captureNativeTokens(collections, variables);
  const fields = {};
  for (const [name, field] of Object.entries(contentTemplate.fields)) {
    const n = await figma.getNodeByIdAsync(field.nodeId);
    if (n?.type !== "TEXT") throw Error("Missing shared text: " + name);
    fields[name] = { ...field, value: n.characters };
  }
  return {
    tokens,
    content: validateContent(
      { schemaVersion: 1, fileKey, fields },
      contentTemplate,
    ),
    collections,
    variables,
  };
}
figma.ui.onmessage = async (message) => {
  try {
    if (message.type === 'exportForest' || message.type === 'importForest') {
      await handleForestMessage(message);
      return;
    }
    const local = await capture();
    const bundle = { tokens: local.tokens, content: local.content };
    if (message.type === "export") {
      figma.ui.postMessage({ type: "tokens", ...bundle });
      return;
    }
    if (message.type !== "import") return;
    if (signature(bundle) !== message.expectedLocalSignature)
      throw Error(
        "Figma changed since comparison. Compare again before importing.",
      );
    const content = validateContent(message.bundle.content, contentTemplate);
    const writes = planTokenImport(
      message.bundle.tokens,
      local.collections,
      local.variables,
    );
    const familyWrites = writes.filter((w) =>
      local.variables
        .find((v) => v.id === w.id)
        ?.resolvedType === "STRING" && !String(w.value).startsWith("cubic-bezier("),
    );
    if (familyWrites.length) {
      const families = new Set(
        familyWrites.flatMap((w) => [w.value, w.current]),
      );
      const fonts = await figma.listAvailableFontsAsync();
      for (const font of fonts.filter((f) => families.has(f.fontName.family)))
        await figma.loadFontAsync(font.fontName);
    }
    const texts = [];
    for (const [name, field] of Object.entries(content.fields)) {
      const n = await figma.getNodeByIdAsync(field.nodeId);
      if (n?.type !== "TEXT") throw Error("Missing shared text");
      if (n.characters !== field.value) {
        const segments = n.getStyledTextSegments(["fontName"]);
        if (!segments.length) segments.push({ fontName: n.fontName });
        for (const part of segments) {
          if (!part.fontName || part.fontName === figma.mixed)
            throw Error(
              "Resolve the missing/mixed font before importing shared text.",
            );
          await figma.loadFontAsync(part.fontName);
        }
        texts.push({ n, old: n.characters, value: field.value });
      }
    }
    // Font loading yields to the editor; protect edits made during preparation.
    const prepared = await capture();
    if (
      signature({ tokens: prepared.tokens, content: prepared.content }) !==
      message.expectedLocalSignature
    )
      throw Error("Figma changed while preparing the import. Compare again.");
    const vs = Object.fromEntries(local.variables.map((v) => [v.id, v]));
    const applied = [],
      edited = [];
    try {
      for (const w of writes) {
        vs[w.id].setValueForMode(w.modeId, w.value);
        applied.push(w);
      }
      for (const t of texts) {
        t.n.characters = t.value;
        edited.push(t);
      }
    } catch (error) {
      for (const t of edited.reverse()) t.n.characters = t.old;
      for (const w of applied.reverse())
        vs[w.id].setValueForMode(w.modeId, w.current);
      throw error;
    }
    const next = await capture();
    figma.ui.postMessage({
      type: "imported",
      tokens: next.tokens,
      content: next.content,
      variableCells: writes.length,
      textNodes: texts.length,
    });
  } catch (error) {
    figma.ui.postMessage({ type: "error", message: error.message });
  }
};

/**
 * Forest-only counterpart to the stable 0.5 token/copy bridge.
 * No component creation, deletion, layout rewriting, or stable token editing.
 */
async function captureForest() {
  if (figma.fileKey && figma.fileKey !== forestTemplate.fileKey)
    throw Error('Wrong Figma file for Forest Lab');
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const c = collections.find(x=>x.name===forestTemplate.collectionName);
  if (!c) throw Error('Forest Lab collection missing. Open the prepared Forest design.');
  const modeByName=Object.fromEntries(c.modes.map(m=>[m.name,m.modeId]));
  if (!modeByName.Dawn || !modeByName.Dusk || c.modes.length!==2)
    throw Error('Forest collection must have only Dawn and Dusk');
  const variables = (await Promise.all(c.variableIds.map(id=>figma.variables.getVariableByIdAsync(id)))).filter(Boolean);
  const byName=new Map(variables.map(v=>[v.name,v]));
  if (variables.length!==FOREST_ROLES.length ||
      FOREST_ROLES.some(name=>byName.get(name)?.resolvedType!=='COLOR'))
    throw Error('Forest variable roles changed; manual mapping review required');
  const modes={};
  for (const mode of ['Dawn','Dusk']) {
    modes[mode]={};
    for (const role of FOREST_ROLES) {
      const value=byName.get(role).valuesByMode[modeByName[mode]];
      if (!value || value.type==='VARIABLE_ALIAS') throw Error('Forest direct palette expected: '+role);
      modes[mode][role]=figmaColorToHex(value);
    }
  }
  const fields={};
  for (const [name,config] of Object.entries(forestTemplate.fields)) {
    const node=await figma.getNodeByIdAsync(config.nodeId);
    if (node?.type!=='TEXT') throw Error('Missing Forest text: '+name);
    let parent=node;
    while(parent && parent.type!=='PAGE') parent=parent.parent;
    if(parent?.id!==forestTemplate.pageId)throw Error('Forest text moved to an unapproved page: '+name);
    fields[name]={...config,pageId:forestTemplate.pageId,value:node.characters};
  }
  return {forest:validateForestContract({
    schemaVersion:1,fileKey:forestTemplate.fileKey,pageId:forestTemplate.pageId,
    collectionName:forestTemplate.collectionName,source:forestTemplate.source,modes,fields
  },forestTemplate), collection:c, modeByName, byName};
}

async function handleForestMessage(message) {
  try {
    const local=await captureForest();
    if(message.type==='exportForest') {
      figma.ui.postMessage({type:'forestSnapshot',forest:local.forest});
      return;
    }
    if(message.type!=='importForest') return;
    if(signature(local.forest)!==message.expectedLocalSignature)
      throw Error('Forest changed since compare; retry after review');
    const candidate=validateForestContract(message.forest,forestTemplate);
    const plan=planForestImport(candidate,local.forest,forestTemplate);
    const textNodes=[];
    for(const field of plan.texts) {
      const node=await figma.getNodeByIdAsync(field.nodeId);
      if(node?.type!=='TEXT')throw Error('Missing Forest edit target');
      const segments=node.getStyledTextSegments(['fontName']);
      if(!segments.length)segments.push({fontName:node.fontName});
      for(const item of segments) {
        if(!item.fontName || item.fontName===figma.mixed)
          throw Error('Unresolved Forest font on '+field.name);
        await figma.loadFontAsync(item.fontName);
      }
      textNodes.push({...field,node});
    }
    const rechecked=await captureForest();
    if(signature(rechecked.forest)!==message.expectedLocalSignature)
      throw Error('Forest changed during font preparation; no write made');
    const changedValues=[], changedTexts=[];
    try {
      for(const cell of plan.values){
        const variable=rechecked.byName.get(cell.role);
        const mode=rechecked.modeByName[cell.mode];
        variable.setValueForMode(mode,hexToFigmaColor(cell.to));
        changedValues.push({...cell,variable,mode});
      }
      for(const field of textNodes){
        field.node.characters=field.to;
        changedTexts.push(field);
      }
    }catch(error){
      for(const field of changedTexts.reverse())field.node.characters=field.from;
      for(const cell of changedValues.reverse())
        cell.variable.setValueForMode(cell.mode,hexToFigmaColor(cell.from));
      throw error;
    }
    const verified=await captureForest();
    if(signature(verified.forest)!==signature(candidate))
      throw Error('Forest verification differs after import. Review Figma manually.');
    figma.ui.postMessage({type:'forestImported',forest:verified.forest,
      variableCells:plan.values.length,textNodes:plan.texts.length});
  }catch(error){
    figma.ui.postMessage({type:'error',message:error.message});
  }
}
