import { readFile, writeFile } from "node:fs/promises";
const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");
const content = JSON.parse(await read("site/content.json"));
const contentTemplate = {
  ...content,
  fields: Object.fromEntries(
    Object.entries(content.fields).map(([key, field]) => [
      key,
      { nodeId: field.nodeId, pageId: field.pageId },
    ]),
  ),
};
const pure = (s) =>
  s
    .replace(/^import .*\n/gm, "")
    .replaceAll("export function ", "function ")
    .replaceAll("export const ", "const ");
const code =
  "/* Generated by scripts/build-plugin.mjs. Edit main.js and shared contract modules. */\n" +
  pure(await read("scripts/figma/token-contract.mjs")) +
  "\n" +
  pure(await read("scripts/figma/roundtrip.mjs")) +
  "\nconst contentTemplate=" +
  JSON.stringify(contentTemplate) +
  ";\n" +
  (await read("design/figma/plugin/main.js"));
await writeFile(new URL("design/figma/plugin/code.js", root), code);

const ui = await read("design/figma/plugin/ui-shell.html");
const shared =
  pure(await read("scripts/figma/token-contract.mjs")) +
  "\n" +
  pure(await read("scripts/figma/roundtrip.mjs")) +
  "\nconst contentTemplate=" +
  JSON.stringify(contentTemplate) +
  ";\n" +
  (await read("design/figma/plugin/ui-main.js"));
await writeFile(
  new URL("design/figma/plugin/ui.html", root),
  ui.replace("/*SHARED_SCRIPT*/", shared),
);
